# Generated by Django 5.2.6 on 2025-10-02 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id_antecedente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'antecedente',
            },
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id_arma', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField()),
                ('custo', models.IntegerField()),
                ('peso', models.FloatField()),
                ('numero_dado_dano', models.IntegerField()),
                ('dado_dano', models.IntegerField()),
                ('tipo_dano', models.CharField()),
            ],
            options={
                'db_table': 'arma',
            },
        ),
        migrations.CreateModel(
            name='Armadura',
            fields=[
                ('id_armadura', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('descricao', models.TextField()),
                ('classe_de_armadura', models.IntegerField()),
                ('forca', models.IntegerField()),
                ('furtividade_desvantagem', models.BooleanField()),
                ('peso', models.IntegerField()),
                ('custo', models.IntegerField()),
            ],
            options={
                'db_table': 'armadura',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('descricao', models.TextField()),
                ('hp_n_dados', models.IntegerField()),
                ('hp_dado', models.IntegerField()),
                ('hb_base', models.IntegerField()),
                ('hp_modificador', models.CharField()),
                ('nivel', models.IntegerField()),
            ],
            options={
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='ConjuntoEquipamento',
            fields=[
                ('id_conjunto_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'conjunto_equipamento',
            },
        ),
        migrations.CreateModel(
            name='EquipamentoDeAventura',
            fields=[
                ('id_equipamento_de_aventura', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('custo', models.IntegerField()),
                ('peso', models.FloatField()),
            ],
            options={
                'db_table': 'equipamento_de_aventura',
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id_ferramenta', models.AutoField(primary_key=True, serialize=False)),
                ('nome_ferramenta', models.CharField()),
                ('custo', models.IntegerField()),
                ('peso', models.IntegerField()),
            ],
            options={
                'db_table': 'ferramenta',
            },
        ),
        migrations.CreateModel(
            name='HabilidadeEspecial',
            fields=[
                ('id_habilidade_especial', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'habilidade_especial',
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'idiomas',
            },
        ),
        migrations.CreateModel(
            name='IncrementoHabilidade',
            fields=[
                ('id_incremento_habilidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('valor_incremento', models.IntegerField()),
            ],
            options={
                'db_table': 'incremento_habilidade',
            },
        ),
        migrations.CreateModel(
            name='Magia',
            fields=[
                ('id_magia', models.AutoField(primary_key=True, serialize=False)),
                ('id_truques', models.IntegerField(blank=True, null=True)),
                ('escola', models.CharField()),
                ('tempo_conjuracao', models.CharField()),
                ('alcance', models.IntegerField()),
                ('componentes', models.CharField()),
                ('duraca', models.CharField()),
                ('descricao', models.CharField()),
                ('nivel', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'magia',
            },
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id_personagem', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('raca', models.CharField()),
                ('classe', models.CharField()),
                ('antecedente', models.CharField(blank=True, null=True)),
                ('forca', models.IntegerField()),
                ('destreza', models.IntegerField()),
                ('sabedoria', models.IntegerField()),
                ('inteligencia', models.IntegerField()),
                ('carisma', models.IntegerField()),
                ('constituicao', models.IntegerField()),
                ('altura', models.FloatField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('cor_cabelo', models.CharField(blank=True, null=True)),
                ('cor_pele', models.CharField(blank=True, null=True)),
                ('cor_olhos', models.CharField(blank=True, null=True)),
                ('defeitos', models.CharField(blank=True, null=True)),
                ('traco_personalidade', models.CharField(blank=True, null=True)),
                ('ideais', models.CharField(blank=True, null=True)),
                ('ligacoes', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personagem',
            },
        ),
        migrations.CreateModel(
            name='Proficiencia',
            fields=[
                ('id_proficiencia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('tipo', models.CharField()),
            ],
            options={
                'db_table': 'proficiencia',
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id_propriedade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'propriedade',
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id_raca', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('velocidade', models.IntegerField()),
                ('tamanho', models.IntegerField()),
                ('id_subraca', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'raca',
            },
        ),
        migrations.CreateModel(
            name='TipoArmadura',
            fields=[
                ('id_tipo_armadura', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo_armadura', models.CharField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_armadura',
            },
        ),
        migrations.CreateModel(
            name='Truque',
            fields=[
                ('id_truque', models.IntegerField(primary_key=True, serialize=False)),
                ('escola', models.CharField()),
                ('tempo_conjuracao', models.IntegerField()),
                ('alcance', models.IntegerField()),
                ('componentes', models.CharField()),
                ('duracao', models.CharField()),
                ('descricao', models.CharField()),
            ],
            options={
                'db_table': 'truque',
            },
        ),
        migrations.CreateModel(
            name='ArmaHasClasse',
            fields=[
                ('pk', models.CompositePrimaryKey('arma_id', 'classe_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.arma')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classe')),
            ],
            options={
                'db_table': 'arma_has_classe',
            },
        ),
        migrations.CreateModel(
            name='ArmaduraHasClasse',
            fields=[
                ('pk', models.CompositePrimaryKey('armadura_id', 'classe_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('armadura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.armadura')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classe')),
            ],
            options={
                'db_table': 'armadura_has_classe',
            },
        ),
        migrations.CreateModel(
            name='ConjuntoEquipamentoHasClasse',
            fields=[
                ('pk', models.CompositePrimaryKey('conjunto_equipamento_id', 'classe_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classe')),
                ('conjunto_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.conjuntoequipamento')),
            ],
            options={
                'db_table': 'conjunto_equipamento_has_classe',
            },
        ),
        migrations.CreateModel(
            name='AntecedenteHasEquipamentoDeAventura',
            fields=[
                ('pk', models.CompositePrimaryKey('antecedente_id', 'equipamento_de_aventura_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('antecedente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.antecedente')),
                ('equipamento_de_aventura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.equipamentodeaventura')),
            ],
            options={
                'db_table': 'antecedente_has_equipamento_de_aventura',
            },
        ),
        migrations.CreateModel(
            name='EquipamentoDeAventuraHasClasse',
            fields=[
                ('pk', models.CompositePrimaryKey('classe_id', 'equipamento_de_aventura_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classe')),
                ('equipamento_de_aventura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.equipamentodeaventura')),
            ],
            options={
                'db_table': 'equipamento_de_aventura_has_classe',
            },
        ),
        migrations.CreateModel(
            name='EquipamentoDeAventuraHasConjuntoEquipamento',
            fields=[
                ('pk', models.CompositePrimaryKey('conjunto_equipamento_id', 'equipamento_de_aventura_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('conjunto_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.conjuntoequipamento')),
                ('equipamento_de_aventura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.equipamentodeaventura')),
            ],
            options={
                'db_table': 'equipamento_de_aventura_has_conjunto_equipamento',
            },
        ),
        migrations.CreateModel(
            name='AntecedenteHasFerramenta',
            fields=[
                ('pk', models.CompositePrimaryKey('antecedente_id', 'ferramenta_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('antecedente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.antecedente')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ferramenta')),
            ],
            options={
                'db_table': 'antecedente_has_ferramenta',
            },
        ),
        migrations.CreateModel(
            name='FerramentaHasClasse',
            fields=[
                ('pk', models.CompositePrimaryKey('classe_id', 'ferramenta_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classe')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ferramenta')),
            ],
            options={
                'db_table': 'ferramenta_has_classe',
            },
        ),
        migrations.CreateModel(
            name='ArmaHasPersonagem',
            fields=[
                ('pk', models.CompositePrimaryKey('arma_id', 'personagem_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.arma')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.personagem')),
            ],
            options={
                'db_table': 'arma_has_personagem',
            },
        ),
        migrations.CreateModel(
            name='PersonagemHasEquipamentoDeAventura',
            fields=[
                ('pk', models.CompositePrimaryKey('personagem_id', 'equipamento_de_aventura_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('equipamento_de_aventura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.equipamentodeaventura')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.personagem')),
            ],
            options={
                'db_table': 'personagem_has_equipamento_de_aventura',
            },
        ),
        migrations.CreateModel(
            name='PersonagemHasMagia',
            fields=[
                ('pk', models.CompositePrimaryKey('personagem_id', 'magia_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('magia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.magia')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.personagem')),
            ],
            options={
                'db_table': 'personagem_has_magia',
            },
        ),
        migrations.CreateModel(
            name='ClasseHasProficiencia',
            fields=[
                ('pk', models.CompositePrimaryKey('classe_id', 'proficiencia_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classe')),
                ('proficiencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.proficiencia')),
            ],
            options={
                'db_table': 'classe_has_proficiencia',
            },
        ),
        migrations.CreateModel(
            name='AntecedenteHasProficiencia',
            fields=[
                ('pk', models.CompositePrimaryKey('antecedente_id', 'proficiencia_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('antecedente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.antecedente')),
                ('proficiencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.proficiencia')),
            ],
            options={
                'db_table': 'antecedente_has_proficiencia',
            },
        ),
        migrations.CreateModel(
            name='PropriedadeHasArma',
            fields=[
                ('pk', models.CompositePrimaryKey('propriedade_id', 'arma_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.arma')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.propriedade')),
            ],
            options={
                'db_table': 'propriedade_has_arma',
            },
        ),
        migrations.CreateModel(
            name='IdiomaHasRaca',
            fields=[
                ('pk', models.CompositePrimaryKey('idioma_id', 'raca_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.idiomas')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.raca')),
            ],
            options={
                'db_table': 'idioma_has_raca',
            },
        ),
        migrations.CreateModel(
            name='RacaHasHabilidadeEspecial',
            fields=[
                ('pk', models.CompositePrimaryKey('raca_id', 'habilidade_especial_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('habilidade_especial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.habilidadeespecial')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.raca')),
            ],
            options={
                'db_table': 'raca_has_habilidade_especial',
            },
        ),
        migrations.CreateModel(
            name='RacaHasIncrementoHabilidade',
            fields=[
                ('pk', models.CompositePrimaryKey('raca_id', 'incremento_habilidade_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('incremento_habilidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.incrementohabilidade')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.raca')),
            ],
            options={
                'db_table': 'raca_has_incremento_habilidade',
            },
        ),
        migrations.CreateModel(
            name='Subraca',
            fields=[
                ('id_subraca', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.raca')),
            ],
            options={
                'db_table': 'subraca',
            },
        ),
        migrations.AddField(
            model_name='incrementohabilidade',
            name='subraca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subraca'),
        ),
        migrations.AddField(
            model_name='idiomas',
            name='subraca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subraca'),
        ),
        migrations.CreateModel(
            name='SubracaHasHabilidadeEspecial',
            fields=[
                ('pk', models.CompositePrimaryKey('subraca_id', 'habilidade_especial_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('habilidade_especial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.habilidadeespecial')),
                ('subraca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subraca')),
            ],
            options={
                'db_table': 'subraca_has_habilidade_especial',
            },
        ),
        migrations.CreateModel(
            name='PersonagemHasTipoArmadura',
            fields=[
                ('pk', models.CompositePrimaryKey('personagem_id', 'tipo_armadura_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.personagem')),
                ('tipo_armadura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipoarmadura')),
            ],
            options={
                'db_table': 'personagem_has_tipo_armadura',
            },
        ),
        migrations.AddField(
            model_name='armadura',
            name='tipo_armadura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipoarmadura'),
        ),
        migrations.CreateModel(
            name='SubracaHasTruque',
            fields=[
                ('pk', models.CompositePrimaryKey('subraca_id', 'truque_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('subraca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subraca')),
                ('truque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.truque')),
            ],
            options={
                'db_table': 'subraca_has_truque',
            },
        ),
        migrations.CreateModel(
            name='RacaHasTruque',
            fields=[
                ('pk', models.CompositePrimaryKey('raca_id', 'truque_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.raca')),
                ('truque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.truque')),
            ],
            options={
                'db_table': 'raca_has_truque',
            },
        ),
        migrations.CreateModel(
            name='TruqueHasClasse',
            fields=[
                ('pk', models.CompositePrimaryKey('classe_id', 'truque_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classe')),
                ('truque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.truque')),
            ],
            options={
                'db_table': 'truque_has_classe',
            },
        ),
    ]
