# Generated by Django 5.2.6 on 2025-10-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_raca_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='racas/'),
        ),
    ]
