# Generated by Django 5.2.6 on 2025-10-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_raca_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='images/racas/'),
        ),
    ]
