# Generated by Django 5.2.6 on 2025-10-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_raca_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='magia',
            name='nome_magia',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
