# Generated by Django 5.2.6 on 2025-10-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_raca_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='classes/'),
        ),
    ]
