# Generated by Django 5.2.6 on 2025-10-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_magia_nome_magia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magia',
            name='id_truques',
        ),
        migrations.AlterField(
            model_name='raca',
            name='velocidade',
            field=models.FloatField(),
        ),
    ]
