# Generated by Django 5.2.6 on 2025-10-05 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_magia_id_truques_alter_raca_velocidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseHasMagia',
            fields=[
                ('pk', models.CompositePrimaryKey('classe_id', 'magia_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.classe')),
                ('magia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.magia')),
            ],
            options={
                'db_table': 'classe_has_magia',
            },
        ),
    ]
