# Generated by Django 5.2.6 on 2025-10-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_classehasmagia'),
    ]

    operations = [
        migrations.AddField(
            model_name='magia',
            name='classes',
            field=models.ManyToManyField(to='core.classe'),
        ),
        migrations.DeleteModel(
            name='ClasseHasMagia',
        ),
    ]
