# Generated by Django 5.2.6 on 2025-10-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_magia_classes_delete_classehasmagia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magia',
            name='classes',
        ),
        migrations.AddField(
            model_name='magia',
            name='magias',
            field=models.ManyToManyField(to='core.classe'),
        ),
    ]
