# Generated by Django 5.2.6 on 2025-10-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_magia_classes_magia_magias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magia',
            old_name='magias',
            new_name='classe',
        ),
    ]
