# Generated by Django 5.2.6 on 2025-10-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_magias_magia_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='armadura',
            field=models.ManyToManyField(to='core.armadura'),
        ),
        migrations.DeleteModel(
            name='ArmaduraHasClasse',
        ),
    ]
