# Generated by Django 5.2.6 on 2025-10-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_classe_armadura_delete_armadurahasclasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='truque',
            name='classes',
            field=models.ManyToManyField(to='core.classe'),
        ),
        migrations.AddField(
            model_name='truque',
            name='nome_truque',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TruqueHasClasse',
        ),
    ]
