# Generated by Django 5.2.6 on 2025-10-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_truque_classes_truque_nome_truque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truque',
            name='id_truque',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
