# Generated by Django 5.2.6 on 2025-10-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_classe_icone'),
        ('core', '0014_alter_truque_id_truque'),
    ]

    operations = [
    ]
