# Generated by Django 5.2.6 on 2025-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_0006_classe_icone_0014_alter_truque_id_truque'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedente',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='racas/'),
        ),
    ]
