# Generated by Django 5.2.6 on 2025-10-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_antecedente_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raca',
            name='id_subraca',
        ),
        migrations.AddField(
            model_name='raca',
            name='incremento_habilidade',
            field=models.ManyToManyField(to='core.incrementohabilidade'),
        ),
    ]
