# Generated by Django 5.2.6 on 2025-10-24 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_raca_id_subraca_raca_incremento_habilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incrementohabilidade',
            name='subraca',
            field=models.ForeignKey(blank=1, null=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.subraca'),
        ),
    ]
