# Generated by Django 5.2.6 on 2025-11-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_usuario_personagem_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='plano_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id_cobranca', models.AutoField(primary_key=True, serialize=False)),
                ('id_cobranca_externo', models.IntegerField()),
                ('status_cobranca', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'cobranca',
            },
        ),
    ]
