# Generated by Django 5.2.6 on 2025-11-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_usuario_plano_ativo_cobranca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobranca',
            name='id_cobranca',
        ),
        migrations.AddField(
            model_name='cobranca',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
