# Generated by Django 5.2.6 on 2025-11-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_cobranca_id_cobranca_cobranca_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='id_cobranca_externo',
            field=models.CharField(),
        ),
    ]
