# Generated by Django 5.2.6 on 2025-11-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_antecedentehasferramenta_antecedente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='nome',
            field=models.CharField(default='teste'),
            preserve_default=False,
        ),
    ]
