# Generated by Django 5.2.6 on 2025-11-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_antecedentehasferramenta_antecedente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truque',
            name='personagem',
            field=models.ManyToManyField(to='core.personagem'),
        ),
    ]
