# Generated by Django 5.2.6 on 2025-11-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_arma_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoarmadura',
            name='personagem',
            field=models.ManyToManyField(blank=True, null=True, to='core.personagem'),
        ),
    ]
