# Generated by Django 5.2.6 on 2025-11-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_tipoarmadura_personagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoarmadura',
            name='classe',
            field=models.ManyToManyField(blank=True, to='core.classe'),
        ),
    ]
