# Generated by Django 5.2.6 on 2025-11-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_tipoarmadura_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoarmadura',
            name='personagem',
            field=models.ManyToManyField(blank=True, to='core.personagem'),
        ),
    ]
