# Generated by Django 5.2.6 on 2025-11-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_truque_personagem'),
        ('core', '0026_tipoarmadura_classe'),
    ]

    operations = [
    ]
