# Generated by Django 5.2.6 on 2025-11-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_tipoarmadura_personagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='categoria',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamentodeaventura',
            name='antecedente',
            field=models.ManyToManyField(blank=True, to='core.antecedente'),
        ),
        migrations.AlterField(
            model_name='equipamentodeaventura',
            name='classe',
            field=models.ManyToManyField(blank=True, to='core.classe'),
        ),
        migrations.AlterField(
            model_name='equipamentodeaventura',
            name='conjunto_equipamento',
            field=models.ManyToManyField(blank=True, to='core.conjuntoequipamento'),
        ),
    ]
