# Generated by Django 5.2.6 on 2025-11-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_0024_truque_personagem_0026_tipoarmadura_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truque',
            name='personagem',
        ),
        migrations.AlterField(
            model_name='idiomas',
            name='subraca',
            field=models.ForeignKey(blank=1, null=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.subraca'),
        ),
    ]
