# Generated by Django 5.2.6 on 2025-11-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_truque_personagem_alter_idiomas_subraca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magia',
            name='alcance',
            field=models.CharField(),
        ),
    ]
