# Generated by Django 5.2.6 on 2025-11-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ferramenta_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armadura',
            name='peso',
            field=models.FloatField(),
        ),
    ]
