# Generated by Django 5.2.6 on 2025-11-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_magia_alcance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truque',
            name='alcance',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='truque',
            name='tempo_conjuracao',
            field=models.CharField(),
        ),
    ]
