# Generated by Django 5.2.6 on 2025-11-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_truque_alcance_alter_truque_tempo_conjuracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truque',
            name='raca',
            field=models.ManyToManyField(blank=True, null=True, to='core.raca'),
        ),
        migrations.AlterField(
            model_name='truque',
            name='subraca',
            field=models.ManyToManyField(blank=True, null=True, to='core.subraca'),
        ),
    ]
