# Generated by Django 5.2.6 on 2025-11-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_truque_raca_alter_truque_subraca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='antecedente',
            field=models.ManyToManyField(blank=True, null=True, to='core.antecedente'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='classe',
            field=models.ManyToManyField(blank=True, null=True, to='core.classe'),
        ),
    ]
