# Generated by Django 5.2.6 on 2025-11-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_ferramenta_antecedente_alter_ferramenta_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiencia',
            name='antecedente',
            field=models.ManyToManyField(blank=True, null=True, to='core.antecedente'),
        ),
        migrations.AlterField(
            model_name='proficiencia',
            name='classe',
            field=models.ManyToManyField(blank=True, null=True, to='core.classe'),
        ),
    ]
