# Generated by Django 5.2.6 on 2025-11-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_proficiencia_antecedente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='aliados_e_organizacoes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personagem',
            name='aparencia_do_personagem',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personagem',
            name='historia_do_personagem',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personagem',
            name='tesouro',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personagem',
            name='tracos_e_caracteristicas_adicionais',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='cor_cabelo',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='cor_pele',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='cor_olhos',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='defeitos',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='traco_personalidade',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='ideais',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='ligacoes',
        ),

    ]
