# Generated by Django 5.2.6 on 2025-11-25 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_armadura_peso'),
        ('core', '0034_personagem_aliados_e_organizacoes_and_more'),
    ]

    operations = [
    ]
