# Generated by Django 5.2.6 on 2025-11-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20251125_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProficienciaSalvaguardas_Pericias',
            fields=[
                ('id_proficienciaSalvaguardas_pericia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
            ],
            options={
                'db_table': 'proficiencia_salvaguardas_pericias',
            },
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='arma',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='equipamento_de_aventura',
        ),
        migrations.AddField(
            model_name='truque',
            name='personagem',
            field=models.ManyToManyField(blank=True, null=True, to='core.personagem'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='magia',
            field=models.ManyToManyField(blank=True, null=True, to='core.magia'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='proficienciaSalvaguardas_Pericias',
            field=models.ManyToManyField(to='core.proficienciasalvaguardas_pericias'),
        ),
    ]
